theme: jekyll-theme-hacker
title: Dyalect
description: Dyalect, a dynamic language for .NET Core
show_downloads: true
github:
      zip_url: http://example.com/download.zip
      tar_url: http://example.com/download.tar.gz
